import { Injectable, inject } from '@angular/core';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { SupabaseService } from '../../../core/supabase/supabase.service';
import { BranchStore } from '../../../core/branches/branch.store';
import type { LetterTemplate } from '../data/settings-pack.service';

/** Render a letter template to a PDF (A4 portrait).
 *
 *  The renderer is intentionally simple: it strips HTML tags from the
 *  body to a plain-text paragraph stream (preserving <p>, <ul>, <strong>
 *  semantically). For pixel-accurate HTML layout, switch to html2canvas
 *  later — this gives crisp print-quality text for the common cases. */
@Injectable({ providedIn: 'root' })
export class LetterRenderService {
  private readonly supabase = inject(SupabaseService);
  private readonly branchStore = inject(BranchStore);

  /**
   * Render a template with variables filled in.
   * @param tpl       The letter template (body_html with {{var}} placeholders)
   * @param vars      Map of variable name → value
   * @param opts      Optional signatory name + role to render below the body
   * @returns         { blob, fileName } — ready to download or upload
   */
  async render(
    tpl: LetterTemplate,
    vars: Record<string, string | number>,
    opts: {
      signatoryName?: string;
      signatoryRole?: string;
      signatureDataUrl?: string | null;
      autoPrint?: boolean;
    } = {},
  ): Promise<{ blob: Blob; fileName: string }> {
    const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 18;
    let cursorY = margin;

    // ── Header: branch name + tagline (if available) ────────────────
    const branch = this.branchStore.activeBranch();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(11, 95, 174);  // primary blue
    doc.text(branch?.name ?? 'Sree Diagnostics', pageW / 2, cursorY, { align: 'center' });
    cursorY += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128);
    doc.text(tpl.category.toUpperCase() + ' · ' + tpl.name, pageW / 2, cursorY, { align: 'center' });
    cursorY += 4;
    doc.setDrawColor(229, 231, 235);
    doc.line(margin, cursorY, pageW - margin, cursorY);
    cursorY += 8;

    // ── Date strip ──────────────────────────────────────────────────
    doc.setFontSize(10);
    doc.setTextColor(17, 24, 39);
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}`,
             pageW - margin, cursorY, { align: 'right' });
    cursorY += 7;

    // ── Body: substitute vars, then walk the HTML as paragraphs ─────
    const filled = this.applyVars(tpl.body_html, vars);
    const blocks = this.htmlToBlocks(filled);

    doc.setFontSize(11);
    doc.setTextColor(17, 24, 39);
    for (const block of blocks) {
      if (cursorY > pageH - 40) {  // page break with bottom margin for sig
        doc.addPage();
        cursorY = margin;
      }
      const lines = doc.splitTextToSize(block.text, pageW - margin * 2);
      if (block.bold) doc.setFont('helvetica', 'bold');
      else            doc.setFont('helvetica', 'normal');
      doc.text(lines, margin + (block.bullet ? 6 : 0), cursorY);
      if (block.bullet) {
        doc.text('•', margin, cursorY);
      }
      cursorY += lines.length * 5 + 2;
    }

    // ── Signature block ─────────────────────────────────────────────
    cursorY = Math.max(cursorY + 10, pageH - 50);
    if (opts.signatureDataUrl) {
      try {
        doc.addImage(opts.signatureDataUrl, 'PNG', margin, cursorY, 40, 18);
      } catch { /* swallow bad-image errors */ }
      cursorY += 20;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(17, 24, 39);
    doc.text(opts.signatoryName ?? '___________________________', margin, cursorY);
    cursorY += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128);
    doc.text(opts.signatoryRole ?? tpl.default_signatory_role ?? '', margin, cursorY);

    // ── Footer ──────────────────────────────────────────────────────
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Generated by Niyamone Lab · ${branch?.name ?? ''} · ${new Date().toISOString()}`,
      pageW / 2, pageH - 8, { align: 'center' },
    );

    const fileName = `${tpl.code}_${new Date().toISOString().slice(0, 10)}.pdf`;
    const blob = doc.output('blob');

    if (opts.autoPrint) {
      const url = URL.createObjectURL(blob);
      const w = window.open(url);
      w?.addEventListener('load', () => w.print());
    }

    return { blob, fileName };
  }

  /** Replace {{var}} placeholders with values (HTML-safe text). */
  private applyVars(html: string, vars: Record<string, string | number>): string {
    return html.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (_, key) => {
      const v = vars[key];
      return v == null ? `[${key}]` : String(v);
    });
  }

  /** Tokenise HTML body into a stream of {text, bold, bullet} blocks. */
  private htmlToBlocks(html: string): Array<{ text: string; bold?: boolean; bullet?: boolean }> {
    const out: Array<{ text: string; bold?: boolean; bullet?: boolean }> = [];
    // strip everything to text-only with markers for <strong> and <li>
    const normalised = html
      .replace(/<br\s*\/?\s*>/gi, '\n')
      .replace(/<p[^>]*>/gi, '')
      .replace(/<\/p>/gi, '\n\n')
      .replace(/<li[^>]*>/gi, '__BULLET__')
      .replace(/<\/li>/gi, '\n')
      .replace(/<\/?ul[^>]*>/gi, '\n')
      .replace(/<\/?ol[^>]*>/gi, '\n')
      .replace(/<strong[^>]*>(.*?)<\/strong>/gi, '__BOLD__$1__/BOLD__')
      .replace(/<b[^>]*>(.*?)<\/b>/gi, '__BOLD__$1__/BOLD__')
      .replace(/<[^>]+>/g, '')      // strip remaining tags
      .replace(/&nbsp;/g, ' ')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&#39;|&apos;/g, "'")
      .replace(/&quot;/g, '"');

    const paragraphs = normalised.split(/\n\n+/);
    for (const para of paragraphs) {
      const trimmed = para.trim();
      if (!trimmed) continue;
      const isBullet = trimmed.startsWith('__BULLET__');
      const text = trimmed.replace(/^__BULLET__/, '').replace(/__BOLD__|__\/BOLD__/g, '');
      out.push({ text, bullet: isBullet });
    }
    return out;
  }

  /** Trigger download of a Blob in the browser. */
  download(blob: Blob, fileName: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
}
