import { Injectable, inject } from '@angular/core';
import { LabComplianceService, type PeriodSummary } from '../data/lab-compliance.service';
import { AuthStore } from '../../../core/auth/auth.store';
import { BranchStore } from '../../../core/branches/branch.store';
import {
  HospitalSettingsService, type HospitalSettings,
} from '../../pharmacy/services/hospital-settings.service';

interface PackInput {
  fromIso: string;
  toIso: string;
  branchId: string | null;
}

/**
 * Builds the NABL/CAP audit pack — one self-contained printable HTML window
 * the user can save as PDF via the browser print dialog. Sections:
 *   1. Cover page (period, branch, generated by, hospital identity)
 *   2. Period summary (cards)
 *   3. QC runs ledger
 *   4. Shift compliance
 *   5. Calibrations
 *   6. Critical alerts
 *   7. Sample rejections
 */
@Injectable({ providedIn: 'root' })
export class LabAuditPackService {
  private compliance = inject(LabComplianceService);
  private auth       = inject(AuthStore);
  private branch     = inject(BranchStore);
  private settingsSvc = inject(HospitalSettingsService);

  async open(input: PackInput): Promise<void> {
    const settingsPromise = input.branchId
      ? this.settingsSvc.loadSettings(input.branchId).catch(() => null as HospitalSettings | null)
      : Promise.resolve<HospitalSettings | null>(this.settingsSvc.getSettings());

    const [summary, runs, shifts, calibrations, criticals, rejections, settings] = await Promise.all([
      this.compliance.periodSummary(input.fromIso, input.toIso, input.branchId),
      this.compliance.exportSection(input.fromIso, input.toIso, input.branchId, 'runs'),
      this.compliance.exportSection(input.fromIso, input.toIso, input.branchId, 'shifts'),
      this.compliance.exportSection(input.fromIso, input.toIso, input.branchId, 'calibrations'),
      this.compliance.exportSection(input.fromIso, input.toIso, input.branchId, 'critical_alerts'),
      this.compliance.exportSection(input.fromIso, input.toIso, input.branchId, 'rejections'),
      settingsPromise,
    ]);

    const html = this.buildHtml({
      input, summary, runs, shifts, calibrations, criticals, rejections,
      settings: settings ?? this.fallbackSettings(input.branchId ?? ''),
      generatedBy: this.auth.claims().email ?? '—',
      branchName:  this.branch.activeBranchName(),
    });

    const win = window.open('', '_blank', 'width=1080,height=1200,scrollbars=yes');
    if (!win) {
      alert('Allow popups to download the audit pack.');
      return;
    }
    win.document.open();
    win.document.write(html);
    win.document.close();
  }

  // ── HTML composition ────────────────────────────────────────────
  private buildHtml(p: {
    input: PackInput;
    summary: PeriodSummary;
    runs: any[]; shifts: any[]; calibrations: any[]; criticals: any[]; rejections: any[];
    settings: HospitalSettings;
    generatedBy: string;
    branchName: string;
  }): string {
    const fmtDate = (iso: string | null | undefined) => {
      if (!iso) return '—';
      try { return new Date(iso).toLocaleString('en-IN',
        { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }); }
      catch { return iso; }
    };
    const fmtDay = (iso: string) => {
      try { return new Date(iso).toLocaleDateString('en-IN',
        { day: '2-digit', month: 'short', year: 'numeric' }); }
      catch { return iso; }
    };
    const periodLabel = `${fmtDay(p.input.fromIso)} → ${fmtDay(p.input.toIso)}`;
    const generatedAt = fmtDate(new Date().toISOString());

    const safe = (v: any) => {
      if (v === null || v === undefined) return '<span class="muted">—</span>';
      const s = String(v);
      return s.replace(/[<>&"]/g, c => ({ '<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;' }[c] as string));
    };
    const arr = (v: any) => Array.isArray(v) ? v.join(', ') : (v ?? '');

    const summaryCards = `
      <section class="grid">
        <div class="card">
          <div class="card-h">QC runs</div>
          <div class="card-big">${p.summary.runs.total}</div>
          <div class="card-row"><span>Accepted</span><strong class="ok">${p.summary.runs.accepted} (${p.summary.runs.pct_accepted}%)</strong></div>
          <div class="card-row"><span>Warning</span><strong class="warn">${p.summary.runs.warning} (${p.summary.runs.pct_warning}%)</strong></div>
          <div class="card-row"><span>Rejected</span><strong class="bad">${p.summary.runs.rejected} (${p.summary.runs.pct_rejected}%)</strong></div>
        </div>
        <div class="card">
          <div class="card-h">Top violations</div>
          ${p.summary.top_violations.length === 0 ? '<div class="muted">None</div>' :
            p.summary.top_violations.map(v => `
              <div class="card-row"><span>${safe(v.instrument_code)} · <code>${safe(v.rule)}</code></span><strong>${v.count}</strong></div>
            `).join('')}
        </div>
        <div class="card">
          <div class="card-h">Calibrations</div>
          <div class="card-row"><span>Performed in window</span><strong>${p.summary.calibrations.performed_in_window}</strong></div>
          <div class="card-row"><span>Overdue right now</span><strong class="${p.summary.calibrations.overdue_now > 0 ? 'bad' : 'ok'}">${p.summary.calibrations.overdue_now}</strong></div>
        </div>
        <div class="card">
          <div class="card-h">Critical alerts</div>
          <div class="card-row"><span>Total raised</span><strong>${p.summary.critical_alerts.total}</strong></div>
          <div class="card-row"><span>Acknowledged</span><strong class="ok">${p.summary.critical_alerts.acknowledged}</strong></div>
          <div class="card-row"><span>Median ack TAT</span><strong>${p.summary.critical_alerts.median_ack_minutes != null ? Number(p.summary.critical_alerts.median_ack_minutes).toFixed(1) + ' min' : '—'}</strong></div>
        </div>
        <div class="card">
          <div class="card-h">Sample rejections</div>
          <div class="card-row"><span>Total</span><strong>${p.summary.rejections.total}</strong></div>
          ${p.summary.rejections.by_reason.slice(0,3).map(r => `
            <div class="card-row"><span>${safe(r.reason)}</span><strong>${r.count}</strong></div>
          `).join('')}
        </div>
        <div class="card">
          <div class="card-h">Shift compliance</div>
          <div class="card-row"><span>Total shifts</span><strong>${p.summary.shifts.total}</strong></div>
          <div class="card-row"><span>QC cleared</span><strong class="ok">${p.summary.shifts.cleared}</strong></div>
          <div class="card-row"><span>Closed without clear</span><strong class="${p.summary.shifts.closed_without_qc_clear > 0 ? 'bad' : 'ok'}">${p.summary.shifts.closed_without_qc_clear}</strong></div>
          <div class="card-row"><span>Avg time-to-clear</span><strong>${p.summary.shifts.avg_time_to_clear_minutes ?? '—'} min</strong></div>
        </div>
      </section>
    `;

    const runsTable = p.runs.length === 0 ? '<p class="muted">No QC runs in this window.</p>' : `
      <table>
        <thead><tr>
          <th>Measured</th><th>Instrument</th><th>Test</th><th>Lot · level</th>
          <th class="num">μ ± SD</th><th class="num">Value</th><th class="num">SD</th>
          <th>Status</th><th>Violations</th><th>Action taken</th><th>Run by</th>
        </tr></thead>
        <tbody>
          ${p.runs.map(r => `
            <tr class="status-${safe(r.run_status)}">
              <td>${fmtDate(r.measured_at)}</td>
              <td>${safe(r.instrument_code)}</td>
              <td>${safe(r.test_code)}</td>
              <td>${safe(r.material_lot)} · ${safe(r.material_level)}</td>
              <td class="num">${safe(r.mean_target)} ± ${safe(r.sd_target)}</td>
              <td class="num">${safe(r.value)}</td>
              <td class="num">${r.deviation_sd != null ? Number(r.deviation_sd).toFixed(2) : '—'}</td>
              <td><span class="pill ${safe(r.run_status)}">${safe(r.run_status)}</span></td>
              <td>${safe(arr(r.violations))}</td>
              <td>${safe(r.action_taken)}</td>
              <td>${safe(r.ran_by_full_name)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;

    const shiftsTable = p.shifts.length === 0 ? '<p class="muted">No shift sessions in this window.</p>' : `
      <table>
        <thead><tr>
          <th>Opened</th><th>Staff</th><th>Role</th><th>Overdue at open</th>
          <th>QC cleared</th><th class="num">TTC (min)</th><th>Closed</th><th class="num">Length (min)</th><th>Status</th>
        </tr></thead>
        <tbody>
          ${p.shifts.map(s => `
            <tr class="${s.closed_without_qc_clear ? 'shift-bad' : ''}">
              <td>${fmtDate(s.opened_at)}</td>
              <td>${safe(s.staff_name)}</td>
              <td>${safe(s.staff_role)}</td>
              <td>${safe(arr(s.qc_overdue_snapshot))}</td>
              <td>${fmtDate(s.qc_cleared_at)}</td>
              <td class="num">${safe(s.time_to_clear_minutes)}</td>
              <td>${fmtDate(s.closed_at)}</td>
              <td class="num">${safe(s.shift_length_minutes)}</td>
              <td>${s.closed_without_qc_clear ? '<span class="pill rejected">NABL gap</span>' :
                  s.qc_was_cleared ? '<span class="pill accepted">Cleared</span>' :
                  !s.closed_at ? '<span class="pill warning">Open</span>' :
                  '<span class="pill">Closed</span>'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;

    const calTable = p.calibrations.length === 0 ? '<p class="muted">No calibrations in this window.</p>' : `
      <table>
        <thead><tr>
          <th>Performed</th><th>Instrument</th><th>Type</th><th>Result</th>
          <th>Next due</th><th>Certificate #</th><th>Performed by</th><th>Notes</th>
        </tr></thead>
        <tbody>
          ${p.calibrations.map(c => `
            <tr>
              <td>${fmtDate(c.performed_at)}</td>
              <td>${safe(c.instrument_code)}</td>
              <td>${safe(c.calibration_type)}</td>
              <td><span class="pill ${c.result === 'pass' ? 'accepted' : 'rejected'}">${safe(c.result)}</span></td>
              <td>${fmtDate(c.next_due_at)}</td>
              <td>${safe(c.certificate_no)}</td>
              <td>${safe(c.performed_by_name)}</td>
              <td>${safe(c.notes)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;

    const critTable = p.criticals.length === 0 ? '<p class="muted">No critical alerts in this window.</p>' : `
      <table>
        <thead><tr>
          <th>Raised</th><th>Test</th><th class="num">Value</th><th>Reference</th>
          <th>Notified</th><th>Acknowledged</th><th>Closed</th><th>Status</th>
        </tr></thead>
        <tbody>
          ${p.criticals.map(a => `
            <tr>
              <td>${fmtDate(a.raised_at)}</td>
              <td>${safe(a.test_name)}</td>
              <td class="num">${safe(a.value_numeric ?? a.value_text)}</td>
              <td>${safe(a.reference_low)} – ${safe(a.reference_high)}</td>
              <td>${fmtDate(a.notified_at)} ${a.notified_via ? '· ' + safe(a.notified_via) : ''}</td>
              <td>${fmtDate(a.acknowledged_at)}</td>
              <td>${fmtDate(a.closed_at)}</td>
              <td>${safe(a.status)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;

    const rejTable = p.rejections.length === 0 ? '<p class="muted">No sample rejections in this window.</p>' : `
      <table>
        <thead><tr>
          <th>Rejected at</th><th>Reason</th><th>Details</th><th>Test codes</th>
          <th>Specimen</th><th>Rejected by</th><th>Recollected at</th>
        </tr></thead>
        <tbody>
          ${p.rejections.map(r => `
            <tr>
              <td>${fmtDate(r.rejected_at)}</td>
              <td>${safe(r.reason)}</td>
              <td>${safe(r.reason_details)}</td>
              <td>${safe(arr(r.test_codes))}</td>
              <td>${safe(r.specimen_type)}</td>
              <td>${safe(r.rejected_by_name)}</td>
              <td>${fmtDate(r.recollection_at)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;

    return `<!DOCTYPE html>
<html><head>
<meta charset="utf-8"/>
<title>Lab QC Audit Pack · ${safe(p.settings.hospital_name)} · ${periodLabel}</title>
<style>
  @page { size: A4 landscape; margin: 12mm 10mm; }
  body { font: 11px/1.4 'Inter', Arial, sans-serif; color: #1a1f2e; background: #fff; margin: 0; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  h2 { font-size: 15px; margin: 18px 0 6px; padding-bottom: 4px; border-bottom: 1.5px solid #1a3a6b; color: #1a3a6b; }
  .cover { padding: 18mm 0; text-align: center; page-break-after: always; }
  .cover .logo { font-size: 28px; font-weight: 700; color: #1a3a6b; }
  .cover .meta { margin-top: 10mm; }
  .cover .meta p { margin: 4px 0; }
  .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 6px 24px; max-width: 480px; margin: 8mm auto 0; text-align: left; font-size: 12px; }
  .meta-grid dt { color: #555; }
  .meta-grid dd { margin: 0; font-weight: 600; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }
  .card { border: 1px solid #ccd; border-radius: 6px; padding: 10px; page-break-inside: avoid; }
  .card-h { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: #556; margin-bottom: 4px; }
  .card-big { font-size: 28px; font-weight: 700; color: #1a3a6b; line-height: 1; margin-bottom: 6px; }
  .card-row { display: flex; justify-content: space-between; padding: 2px 0; border-top: 1px dashed #e3e6ef; font-size: 11px; }
  .card-row:first-of-type { border-top: 0; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 14px; font-size: 10px; }
  thead { background: #f4f6fb; }
  th, td { padding: 4px 6px; border: 1px solid #d8dde9; text-align: left; vertical-align: top; }
  th { font-size: 9px; text-transform: uppercase; letter-spacing: 0.04em; color: #4a5266; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; font-family: ui-monospace, monospace; }
  .pill { display: inline-block; padding: 1px 6px; border-radius: 8px; font-size: 9px; font-weight: 600; text-transform: uppercase; }
  .pill.accepted { background: #d4f1d4; color: #14672a; }
  .pill.warning  { background: #fde8c4; color: #8a4a06; }
  .pill.rejected { background: #fad7d2; color: #8a1c14; }
  .pill { background: #e6e9f0; color: #41475a; }
  .ok { color: #14672a; }
  .warn { color: #8a4a06; }
  .bad { color: #8a1c14; }
  .muted { color: #888; }
  .shift-bad { background: #fbe8e6; }
  tr.status-rejected { background: #fdf3f2; }
  tr.status-warning  { background: #fff8ec; }
  section.section { page-break-before: always; }
  footer { position: fixed; bottom: 5mm; left: 0; right: 0; font-size: 9px; color: #888; text-align: center; }
  .actions { position: fixed; top: 8px; right: 8px; }
  .actions button { font: 12px Inter, Arial, sans-serif; padding: 6px 12px; border-radius: 6px; border: 1px solid #1a3a6b; background: #1a3a6b; color: #fff; cursor: pointer; }
  @media print { .actions { display: none; } }
</style>
</head><body>
  <div class="actions">
    <button onclick="window.print()">🖨 Save as PDF / Print</button>
  </div>

  <!-- ───────── Cover ───────── -->
  <section class="cover">
    <div class="logo">${safe(p.settings.hospital_name)}</div>
    <p style="font-size: 13px; color: #555; margin: 4px 0;">${safe(p.settings.hospital_tagline ?? '')}</p>
    <h1 style="margin-top: 14mm;">Lab QC &amp; Compliance Audit Pack</h1>
    <p style="font-size: 13px; color: #555;">NABL · CAP supporting evidence</p>
    <dl class="meta-grid">
      <dt>Period</dt>           <dd>${periodLabel}</dd>
      <dt>Branch</dt>            <dd>${safe(p.branchName)}</dd>
      <dt>Generated at</dt>      <dd>${generatedAt}</dd>
      <dt>Generated by</dt>      <dd>${safe(p.generatedBy)}</dd>
      <dt>Drug licence (retail)</dt> <dd>${safe(p.settings.drug_license_retail_number)}</dd>
      <dt>GST number</dt>        <dd>${safe(p.settings.gst_number)}</dd>
      <dt>Hospital reg #</dt>    <dd>${safe(p.settings.hospital_registration_number)}</dd>
      <dt>QC retention policy</dt><dd>2 years (rolling)</dd>
    </dl>
    <p style="margin-top: 14mm; font-size: 11px; color: #777;">
      This pack contains every QC run, shift session, calibration, critical-value alert, and sample rejection
      recorded in the period above for the named branch. Records are append-only — modifications are restricted
      to corrective-action annotations only.
    </p>
  </section>

  <!-- ───────── Period summary ───────── -->
  <section class="section">
    <h2>1 · Period summary</h2>
    ${summaryCards}
  </section>

  <!-- ───────── QC runs ───────── -->
  <section class="section">
    <h2>2 · QC runs ledger (${p.runs.length})</h2>
    ${runsTable}
  </section>

  <!-- ───────── Shift compliance ───────── -->
  <section class="section">
    <h2>3 · Shift compliance (${p.shifts.length})</h2>
    ${shiftsTable}
  </section>

  <!-- ───────── Calibrations ───────── -->
  <section class="section">
    <h2>4 · Calibrations (${p.calibrations.length})</h2>
    ${calTable}
  </section>

  <!-- ───────── Critical alerts ───────── -->
  <section class="section">
    <h2>5 · Critical-value alerts (${p.criticals.length})</h2>
    ${critTable}
  </section>

  <!-- ───────── Sample rejections ───────── -->
  <section class="section">
    <h2>6 · Sample rejections (${p.rejections.length})</h2>
    ${rejTable}
  </section>

  <footer>${safe(p.settings.hospital_name)} · Audit pack · ${periodLabel} · Generated ${generatedAt}</footer>
</body></html>`;
  }

  private fallbackSettings(branchId: string): HospitalSettings {
    return {
      branch_id: branchId,
      hospital_name: 'Sree Diagnostics',
      pharmacy_name: 'Sree Diagnostics',
    };
  }
}
